<?php

return [
	'BrUtAlBuLlz',
	'BΛ PapaGolf',
	'Dunkler Tyrann',
	'FraX',
	'Galen Marek',
	'Garibaldi',
	'HEXE',
	'JB6',
	'Jon Dampfdiagramm',
	'Karrambaa',
	'Kelle',
	'Koradun Boradon',
	'Machete',
	'massefrosch',
	'MeegaRipcheen',
	'Psychoschaaf',
	'SmokeLO',
	'Sonnengott Ra',
	'Tison92',
	'Valar Morghulis',
	'BΛ 41 Lead JohnGodlike',
	'Darthtrayan',
	'McBurns',
	'BΛ McDuke',
	'Icewolf',
	'Syris Gorn',
	'KingBojan',
	'hayvan',
	'Mol H2O',
	'Polinho',
	'limexx',
	'Akku',
	'Anwalt',
	'BaboHulk',
	'DaSaSto',
	'DΛrth JΛkz',
	'BΛ NΛDJΛ 4802',
	'SoontirFel',
	'Wusel',
	'TrymyBest',
	'Flobstar',
	'Subzilla',
	'Targaryen',
	'BuzzT',
	'Lapaluzza',
	'BΛ Wolfman1408',
	'DK Kalle',
	'Kvothe',
	'Wyrdn',
	'RageFury1',
	'Deadpoet',
	'Punti',
	'TommyReini',
	'Galaktischer',
	'BΛ 442nd Deathtrooper',
	'BΛ 442nd Zahariel',
	'BΛ Kal Lo Ryan',
	'TREX316',
	'Bullet',
	'R2 D2',
	'nick00',
	'Cerebro',
	'BΛ torexx',
	'BΛ 442nd Ardoran',
	'Wes Jamson',
	'Karis Lor',
	'MaXiMuM',
	'Buraki',
	'Flori Wan Knobi',
	'Motschi89',
	'Buttina',
	'Duc Nguyen',
	'Pollux',
	'BΛ 442nd lole',
	'HaihappenUhaha',
	'Vargur',
	'BΛ 442nd Dark Vaper',
	'BΛ Wiedster',
	'BΛ Alafin',
	'BΛ St4rkill3r',
	'ΒΛ 442nd Salomonjr',
	'Gustavo',
	'OpiFS',
	'Itami',
	'Nightfighter',
	'BΛ Guardien',
	'BΛ Venox',
	'Fussel',
	'DerRumrotz',
	'Buschi',
	'Blindworm',
	'Mycr',
	'DNA',
	'Herold Blaster',
	'PaulTailor',
	'BA SaniT',
	'Algrunar',
	'BΛ Tailerukh',
	'Agent Horstus Handabhacker',
	'BΛ RamJamRodigan',
	'Rosen',
	'Gl0r10us',
	'Cucpower',
	'Spitz',
	'franklynn',
	'DrUniverso',
	'BΛ CyrusXS',
	'Trinity',
	'Ravek',
	'BΛ NΛDJΛ 4802',
	'BΛ Hansoo',
	'Jakz Teller',
	'FuThis',
	'BΛ Sigi',
	'Nick',
	'VaderSeinVadder',
	'Radhad',
	'Tekman',
	'Rui Vuusen',
	'ΒΛ Abunille',
	'Chris Leeman',
	'AkiraFFM',
	'Ren',
	'BΛ Valuan',
	'Sheherazade',
	'BΛ Limon',
];